### ISSUE TITLE
Error executing example

### ISSUE THREAD

**Issue by rsegura** [kaiwaehner/kafka-streams-machine-learning-examples#4]
Hi,

First, congrats for this examples.

I have a problem when trying to execute the example. This is the error:

> Exception in thread "main" java.lang.ClassNotFoundException: com.github.megachucky.kafka.streams.machinelearning.modelss.gbm_pojo_test
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Unknown Source)
>         at com.github.megachucky.kafka.streams.machinelearning.Kafka_Streams_MachineLearning_H2O_GBM_Example.main(Kafka_Streams_MachineLearning_H2O_GBM_Example.java:38)

Do I need to do something special with the POJO?

Thanks,

**Comment by kaiwaehner** [comment]
Sorry for late response, @rsegura . I did not get an email notification. 

No, there is no need to do anything special.

Do you get this during Maven build or when running the Main class by yourself? 

If not during Maven build, can you please check if your "fat jar" has the class included?

I tried it again on my Macbook. Works fine from scratch with new checkout.

**Comment by kaiwaehner** [comment]
I upgraded to the recent Kafka release 2.0 and tested again. Still working fine for me. Please try again and let me know. Thank you.

**Comment by bismarckz** [comment]
Hi, 
Thank for Share, 
I have installed jdk1.8.0_181 and kafka 2 with zookeeper and reinicied
Apache Maven 3.5.2 
but  i have a problem when trying to execute mvn compile package

Results :

Tests in error:
  com.github.megachucky.kafka.streams.machinelearning.test.Kafka_Streams_MachineLearning_DL4J_DeepLearning_Iris_IntegrationTest: java.nio.file.FileSystemException: C:\Users\-----\AppData\Local\Temp\junit8850107424176097916\junit8391030063973189677\IrisInputTopic-0\00000000000000000000.timeindex: The process cannot access the file because it is being used (..)nother process.
  com.github.megachucky.kafka.streams.machinelearning.test.Kafka_Streams_MachineLearning_H2O_DeepLearning_Example_IntegrationTest: java.nio.file.FileSystemException: C:\Users\------\AppData\Local\Temp\junit6471400984483457428\junit2268153206073467573\AirlineInputTopic-0\00000000000000000000.timeindex: The process cannot access the file because it is being (..) by another process.
  com.github.megachucky.kafka.streams.machinelearning.test.Kafka_Streams_MachineLearning_H2O_GBM_Example_IntegrationTest: java.nio.file.FileSystemException: C:\Users\-----\AppData\Local\Temp\junit466078204952140194\junit4113150626764005236\AirlineInputTopic-0\00000000000000000000.timeindex: The process cannot access the file because it is being used by an(..)r process.
  shouldRecognizeImages(com.github.megachucky.kafka.streams.machinelearning.test.Kafka_Streams_TensorFlow_Image_Recognition_Example_IntegrationTest): java.nio.file.DirectoryNotEmptyException: \tmp\kafka-streams\kafka-streams-tensorflow-image-recognition-integration-test\0_0
  com.github.megachucky.kafka.streams.machinelearning.test.Kafka_Streams_TensorFlow_Image_Recognition_Example_IntegrationTest: C:\Users\------\AppData\Local\Temp\kafka-1474664452892431010\version-2\log.1: The process cannot access the fil(..)cause it is being used by another process.

Tests run: 8, Failures: 0, Errors: 5, Skipped: 0


I dont know what it is.

**Comment by kaiwaehner** [comment]
Looks like you run this on Windows? 

`C:\Users-----\AppData\Local\Temp\`

Well, I never tested on Windows. Kafka in general does not work on Windows. You often get strange exceptions. For that reason, I recommend to use Linux / Mac all the time (either via VM or cloud - if you have to use Windows OS).

Though, in this case it might be some file / directory issue.
