### ISSUE TITLE
Kafka_Streams_TensorFlow_Image_Recognition_Example fails to compile

### ISSUE THREAD

**Issue by rroyhere** [kaiwaehner/kafka-streams-machine-learning-examples#7]
At 195/196 line it fails to compile as the metod is expected to return an array instead returning a object of Tensor
[196,60] array required, but org.tensorflow.Tensor found****

**Comment by kaiwaehner** [comment]
@rroyhere Strange. Works for me. Build runs through, including compiling the Java class and running the Unit test successfully. I also did not change anything regarding this example last months and many people already tried it out. 
I could assume that a newer TensorFlow version could have some breaking changes, but this projects includes all dependencies and correct versions. 

I assume you just cloned the project and did 'mvn clean package'? 

Can you please give more details: 
- Operating system
- Java version
- Steps to execute the build
- Where is this exception? In the Kafka_Streams_TensorFlow_Image_Recognition_Example.java or in the Unit test?

Thanks.

**Comment by kaiwaehner** [comment]
Got it. This would explain the API changes in TensorFlow. It should work if you use the right version.

I am not totally happy with this example anyway because it uses the low level TensorFlow API. This is very complex for people who just want to see the integration (though, it does its job, showing how to embed a TensorFlow model into Kafka Streams microservice) . 
I will build another example using Keras and TensorFlow, which makes it much easier. This is high priority on my TODO list... :-)
